global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'generator'
    scrape_interval: 1s
    static_configs:
      - targets: ['0.0.0.0:2112']
#  - job_name: 'node_exporter_metrics'
#    scrape_interval: 1s
#    static_configs:
#      - targets: ['0.0.0.0:9100']