name: tests
on:
  push:
  pull_request:

env:
  GO_VERSION: 1.14

jobs:
  test:
    name: all tests
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/loaderbot/loaderbot/go
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          path: go/src/github.com/skudasov/loaderbot
          fetch-depth: 1
      - name: Test
        run: make test
        working-directory: ${{env.GOPATH}}/src/github.com/skudasov/loaderbot
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/loaderbot/loaderbot/go
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          path: go/src/github.com/skudasov/loaderbot
          fetch-depth: 1
      - name: Add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: Install golangci
        run: make golangci
        working-directory: ${{env.GOPATH}}/src/github.com/skudasov/loaderbot
      - name: Run golangci-lint
        run: make lint
        working-directory: ${{env.GOPATH}}/src/github.com/skudasov/loaderbot